### ISSUE TITLE
octokit.authenticate() is deprecated. Use "auth" constructor option instead

### ISSUE THREAD

**Issue by bndynet** [semantic-release/github#156]
Hi, 
I get following errors during running semantic-release version 15.13.3 in Travis CI.  Who can help me to fix it. Thanks in advance.

```
[2:12:43 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/home/travis/build/bndynet/bbootstrap/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:4:16)
    at module.exports (/home/travis/build/bndynet/bbootstrap/node_modules/@semantic-release/github/lib/get-client.js:59:10)
    at module.exports (/home/travis/build/bndynet/bbootstrap/node_modules/@semantic-release/github/lib/verify.js:53:20)
    at verifyConditions (/home/travis/build/bndynet/bbootstrap/node_modules/@semantic-release/github/index.js:24:9)
    at validator (/home/travis/build/bndynet/bbootstrap/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at pReduce (/home/travis/build/bndynet/bbootstrap/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/travis/build/bndynet/bbootstrap/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gr2m** [comment]
I got it

**Comment by gr2m** [comment]
Hmm that seems to have been fixed already via https://github.com/semantic-release/github/releases/tag/v5.2.10

Can you make sure you have the latest version?

```
npm ls @semantic-release/github
```

should show @semantic-release/github@5.2.10. If it doesn’t, make sure to update dependencies

**Comment by bndynet** [comment]
Yes, Thanks for your response. 
**@semantic-release/github** is the default in **semantic-release**. I did not install it manually. Same version **semantic-release@15.13.3** in two projects. Run `npm ls @semantic-release/github`, one show `@semantic-release/github@5.2.9`, another show `@semantic-release/github@5.2.10`.  

Do I need to install @semantic-release/github@5.2.10 manually? @gr2m

**Comment by bndynet** [comment]
Got it. Thanks for your help.
