### ISSUE TITLE
Deprecated "number" parameter.

### ISSUE THREAD

**Issue by ellisio** [semantic-release/github#176]
Our build logs are filling up with several deprecation warnings. It appears the `number` parameter should be replaced with `pull_number` in several places. I attempted to fix this myself and give you a PR, but I'm under a time crunch and this seemed to open a can of worms due to eslint, and other issues exposed down the rabbit hole when updating `number` to `poll_number`.

```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".pullRequests.listCommits()". Use "pull_number" instead
    at Object.keys.forEach.key (/root/terraform-apps/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:73:26)
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as listCommits] (/root/terraform-apps/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:69:26)
    at pFilter (/root/terraform-apps/node_modules/@semantic-release/github/lib/success.js:54:36)
    at pMap (/root/terraform-apps/node_modules/p-filter/index.js:5:46)
    at Promise.resolve.then.el (/root/terraform-apps/node_modules/p-map/index.js:46:16) name: 'Deprecation' }
```

```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".pullRequests.get()". Use "pull_number" instead
    at Object.keys.forEach.key (/root/terraform-apps/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:73:26)
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as get] (/root/terraform-apps/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:69:26)
    at pFilter (/root/terraform-apps/node_modules/@semantic-release/github/lib/success.js:55:50) name: 'Deprecation' }
```

```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.createComment()". Use "issue_number" instead
    at Object.keys.forEach.key (/root/terraform-apps/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:73:26)
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as createComment] (/root/terraform-apps/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:69:26)
    at Promise.all.uniqBy.map (/root/terraform-apps/node_modules/@semantic-release/github/lib/success.js:86:37)
    at Array.map (<anonymous>)
    at module.exports (/root/terraform-apps/node_modules/@semantic-release/github/lib/success.js:74:45) name: 'Deprecation' }
```

**Comment by gr2m** [comment]
fixed via #177
