### ISSUE TITLE
Failures during "success" step of this plugin

### ISSUE THREAD

**Issue by rmevans9** [semantic-release/github#183]
Hello,

I recently was doing updates and one of them was semantic-release. In doing the update I assume something else got updated along the way as I started getting this error when my releases are run:

```
An error occurred while running semantic-release: { HttpError: Empty value for parameter 'number': undefined
    at values.forEach (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:64:15)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach.parameterName (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:38:12)
    at Array.forEach (<anonymous>)
    at validate (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:16:23)
  name: 'HttpError',
  status: 400,
  headers: undefined,
  request: undefined,
  pluginName: '@semantic-release/github' }
{ AggregateError: 
    HttpError: Empty value for parameter 'number': undefined
        at values.forEach (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:64:15)
        at Array.forEach (<anonymous>)
        at Object.keys.forEach.parameterName (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:38:12)
        at Array.forEach (<anonymous>)
        at validate (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:16:23)
    at /home/circleci/repo/node_modules/semantic-release/lib/plugins/pipeline.js:54:11 name: 'AggregateError' }error Command failed with exit code 1.
```

I downgraded semantic-release, @semantic-release/git and @semantic-release/github but I still get these failures. I suspect something else got updated that is used by @semantic-release/github that is causing this error but I am not sure what at this point. Any thoughts on what might be going on?

**Comment by gr2m** [comment]
what do you get when you do `npm ls @octokit/rest`? Compare the versions to `npm info @octokit/rest version`. If they are not the same, try `npm --depth 9999 update`

**Comment by rmevans9** [comment]
@gr2m I was on version 16.16.0 but `npm info @octokit/rest version` showed version 16.27.0. I got all @octokit deps updated and the step of commenting on PRs and Issues started working again. 🎉 

I am wondering why the @octokit dependencies had not updated though 🤔

**Comment by pvdlg** [comment]
@rmevans9 it hasn't been updated probably because you have a `package-lock.json` or `yarn.lock` the dependency to an older version.
You should regenerate (or get rid of) your lockfile so you can get the latest versions of your dependencies.
