### ISSUE TITLE
Use of deprecated parameters in @octokit/rest

### ISSUE THREAD

**Issue by sQVe** [semantic-release/github#194]
Hey :wave:,

Just released something an got a ton of deprecation warnings like: 
```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for ".issues.createComment()". Use "issue_number" instead
    at Object.keys.forEach.key (/home/travis/build/sQVe/30s/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:71:26)
    at Array.forEach (<anonymous>)
    at Object.patchedMethod [as createComment] (/home/travis/build/sQVe/30s/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:67:26)
    at Promise.all.uniqBy.map (/home/travis/build/sQVe/30s/node_modules/@semantic-release/github/lib/success.js:86:37)
    at Array.map (<anonymous>)
    at module.exports (/home/travis/build/sQVe/30s/node_modules/@semantic-release/github/lib/success.js:74:45)
    at <anonymous> name: 'Deprecation' }
```

Above is an example of one of the warnings.

**Comment by gr2m** [comment]
I think that was addressed via https://github.com/semantic-release/github/commit/fa677fad84b5483e93afb10dd9fe67fae0e2afa6. Make sure you have the latest @semantic-release/github version

```
$ npm info @semantic-release/github version
5.2.10
```

Compare to output of `npm ls @semantic-release/github`

**Comment by gr2m** [comment]
Ah actually it’s published to `@semantic-release/github@next` which you won’t get by default.

@pvdlg can we bump the `@latest` dist-tag`?

**Comment by pvdlg** [comment]
Done

**Comment by sQVe** [comment]
@gr2m @pvdlg Awesome. Cheers for the quick response!
