### ISSUE TITLE
ENOGHTOKEN No GitHub token specified. with GITHUB_TOKEN definitely specified

### ISSUE THREAD

**Issue by bionicles** [semantic-release/github#244]
to zip my repo with the name of the release as the name of the file, I need to get the next version using the command line to name the zip. 

`source .env && npx semantic-release -d` fails 

`source .env && echo $GITHUB_TOKEN` works

```
(base) 04:26 PM bitpharma $ npx semantic-release -d
[4:26:16 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.2
[4:26:16 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[4:26:16 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:26:16 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:26:16 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[4:26:16 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[4:26:16 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[4:26:16 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[4:26:17 PM] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
[4:26:19 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[4:26:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[4:26:19 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[4:26:19 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
[4:26:19 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[4:26:19 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository bionicles/bp.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at module.exports (/home/bion/hax/bitpharma/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/home/bion/hax/bitpharma/node_modules/@semantic-release/github/lib/verify.js:85:17)
        at verifyConditions (/home/bion/hax/bitpharma/node_modules/@semantic-release/github/index.js:27:9)
        at validator (/home/bion/hax/bitpharma/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /home/bion/hax/bitpharma/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/home/bion/hax/bitpharma/node_modules/p-reduce/index.js:17:9)
    at /home/bion/hax/bitpharma/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/bion/hax/bitpharma/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/bion/hax/bitpharma/node_modules/semantic-release/index.js:92:3)
    at async module.exports (/home/bion/hax/bitpharma/node_modules/semantic-release/index.js:257:22)
    at async module.exports (/home/bion/hax/bitpharma/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}
```

**Comment by bionicles** [comment]
for whatever reason, this works if you put it in ~/,bashrc and `source ~/.bashrc` (ubuntu 16)

**Comment by bionicles** [comment]
I'm gonna try instead using `git archive` inside @semantic-release/exec

**Comment by gr2m** [comment]
I don't think it's a semantic-release problem ...

Can you try this:

```
source .env && node -p process.env.GITHUB_TOKEN
```

**Comment by bionicles** [comment]
sure

**Comment by bionicles** [comment]
anyway, i think my hackish solution was unnecessary and i'll try with "exec"

**Comment by bionicles** [comment]
heh, i'm dumb. github releases already zip the source, with the release name!
