### ISSUE TITLE
RequestError [HttpError]: Cookies must be enabled to use GitHub.

### ISSUE THREAD

**Issue by kleinfreund** [semantic-release/github#268]
## Current behavior

I set-up a semantic-release workflow via GitHub actions for the repository https://github.com/kleinfreund/vue-accessible-color-picker. On push, the workflow was run and the first version of my package was published (yay!). However, the next step failed (full error below):

```
[semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
```

I’m not sure what to make of this error. I don’t recall reading anything in the getting started documents and articles I followed about some cookie settings I needed to be aware of.

Note that I have both `NPM_TOKEN` and `GH_TOKEN` configured via the secrets settings of the repository in question. The `GH_TOKEN` is a public access token which was created with the `public_repo` permission.

What am I missing from my setup and how can I recover from this botched release?

<details>
<summary>full error</summary>

[semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /home/runner/work/vue-accessible-color-picker/vue-accessible-color-picker/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
  headers: {
    'cache-control': 'no-cache',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com",
    'content-type': 'text/plain; charset=utf-8',
    date: 'Thu, 14 May 2020 17:40:28 GMT',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'set-cookie': '_gh_sess=[REDACTED]; path=/; secure; HttpOnly',
    status: '403 Forbidden',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'X-PJAX, Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-request-id': '0400:0851:57C564:924595:5EBD828C',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://github.com/repos/kleinfreund/vue-accessible-color-picker/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/17.9.0 octokit-core.js/2.5.0 Node.js/12.16.3 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"tag_name":"v1.0.0","name":"v1.0.0","body":"# 1.0.0 (2020-05-14)\\n\\n\\n### Features\\n\\n* implement initial version of vue-accessible-color-picker ([eba7d30](https://github.com/kleinfreund/vue-accessible-color-picker/commit/eba7d3055364c2bcbeaa1a0067df6521050d2d3b))\\n\\n\\n\\n","prerelease":false}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  pluginName: '@semantic-release/github'
}
RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /home/runner/work/vue-accessible-color-picker/vue-accessible-color-picker/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
  headers: {
    'cache-control': 'no-cache',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com",
    'content-type': 'text/plain; charset=utf-8',
    date: 'Thu, 14 May 2020 17:40:28 GMT',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'set-cookie': '_gh_sess=[REDACTED]; path=/; secure; HttpOnly',
    status: '403 Forbidden',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'X-PJAX, Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-request-id': '0400:0851:57C564:924595:5EBD828C',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://github.com/repos/kleinfreund/vue-accessible-color-picker/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/17.9.0 octokit-core.js/2.5.0 Node.js/12.16.3 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"tag_name":"v1.0.0","name":"v1.0.0","body":"# 1.0.0 (2020-05-14)\\n\\n\\n### Features\\n\\n* implement initial version of vue-accessible-color-picker ([eba7d30](https://github.com/kleinfreund/vue-accessible-color-picker/commit/eba7d3055364c2bcbeaa1a0067df6521050d2d3b))\\n\\n\\n\\n","prerelease":false}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  pluginName: '@semantic-release/github'
}
##[error]Process completed with exit code 1.
</details>

## Expected behavior

For this error to not happened

or

for this error to actually tell me something useful (I know this is in particular not a problem with semantic-release).

## Environment

- **semantic-release** version: 17.0.7
- CI environment: GitHub actions
- Plugins used: *none*
- **semantic-release** configuration: https://github.com/kleinfreund/vue-accessible-color-picker/blob/main/release.config.js
- CI logs: https://github.com/kleinfreund/vue-accessible-color-picker/runs/675427677

**Comment by ericsciple** [comment]
@gr2m GITHUB_URL is new and feature flag turned on for some accounts today

**Comment by gr2m** [comment]
Thanks for confirming Eric! I'll workaround it in semantic-release 👍

**Comment by ericsciple** [comment]
It's one of three new env vars set by Actions, to enable scripts in Actions to work against GHES or Dotcom.

For example:

```
curl  -H "Authorization: bearer $GITHUB_TOKEN" --request GET "$GITHUB_API_URL/repos/monalisa/example"
```

Here's the three URLS:

| Environment variable | GHES example                  | Dotcom value                     |
| -------------------- | ----------------------------- | -------------------------------- |
| `GITHUB_URL`         | `https://my-ghes`             | `https://github.com`             |
| `GITHUB_API_URL`     | `https://my-ghes/api/v3`      | `https://api.github.com`         |
| `GITHUB_GRAPHQL_URL` | `https://my-ghes/api/graphql` | `https://api.github.com/graphql` |

**Comment by gr2m** [comment]
> `GITHUB_API_URL`

Fantastic, that makes the workaround much easier 👍

**Comment by ericsciple** [comment]
Let me know if it helps and I can turn off the feature flag (on for a small percentage of accounts). Otherwise if you're close i'll leave it on.

**Comment by gr2m** [comment]
I'm close, thanks #269

**Comment by ENikS** [comment]
I am running version 17.0.7 and looks like it was not fixed. These are [logs](https://github.com/gh-bot/issue-merge-labeler/runs/680191135?check_suite_focus=true) with the same issue

**Comment by kleinfreund** [comment]
@ENikS As far as I understand, the bug was fixed in `@semantic-release/github@7.0.6`, but I’m pretty sure the package semantic-release doesn’t use this version, yet. I believe you need to manually install `@semantic-release/github@7.0.6` in your project to make use of the fix that’s referenced in this issue. I haven’t verified yet whether that works because I don’t want to release the next version of my package, yet.

**Comment by ENikS** [comment]
Got it, thank you

**Comment by ericsciple** [comment]
@ENikS sorry for the disruption.

FYI, we're also turning off the feature flag now so Actions will stop setting GITHUB_URL. We're going to switch to GITHUB_SERVER_URL before re-enabling, so it doesn't conflict with semantic-release/github.

**Comment by rapahaeru** [comment]
i still have this problem.
its publishes the tag in npm and github but not comunicates with github, to update the pull requests etc...

```
2020-05-20T22:20:10.7702373Z [10:20:10 PM] [semantic-release] â€º âœ”  Completed step "publish" of plugin "@semantic-release/npm"
2020-05-20T22:20:10.7703012Z [10:20:10 PM] [semantic-release] â€º â„¹  Start step "publish" of plugin "@semantic-release/github"
2020-05-20T22:20:10.8710449Z [10:20:10 PM] [semantic-release] â€º âœ–  Failed step "publish" of plugin "@semantic-release/github"
2020-05-20T22:20:10.8744320Z [10:20:10 PM] [semantic-release] â€º âœ–  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
2020-05-20T22:20:10.8745870Z     at /home/runner/work/catho-components/catho-components/node_modules/@octokit/request/dist-node/index.js:66:23
2020-05-20T22:20:10.8746684Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2020-05-20T22:20:10.8747273Z   status: 403,
2020-05-20T22:20:10.8747813Z   headers: {
2020-05-20T22:20:10.8749633Z     'cache-control': 'no-cache',
2020-05-20T22:20:10.8750560Z     connection: 'close',
2020-05-20T22:20:10.8751483Z     'content-encoding': 'gzip',
2020-05-20T22:20:10.8755809Z     'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/socket-worker.js",
2020-05-20T22:20:10.8757171Z     'content-type': 'text/plain; charset=utf-8',
2020-05-20T22:20:10.8758175Z     date: 'Wed, 20 May 2020 22:20:10 GMT',
2020-05-20T22:20:10.8759432Z     'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
2020-05-20T22:20:10.8760820Z     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2020-05-20T22:20:10.8761762Z     server: 'GitHub.com',
2020-05-20T22:20:10.8770982Z     'set-cookie': 
```

But my repo is private. Is that a problem?

**Comment by Silthus** [comment]
I have the same problem as @rapahaeru with multiple of my repos. They are all public and use the latest version of the semantic-release packages.

**Comment by Silthus** [comment]
@rapahaeru try setting the GH_URL to https://api.github.com that resolved it for me.

**Comment by rapahaeru** [comment]
@Silthus worked here, thanks so much!

**Comment by hossin43** [comment]
دانلود

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>3CSKmz

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>x6uq7h

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>SjwV4m

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>OtUIGA

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>GYqByI

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ZxtqZe

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>icQcMH

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jmThcu

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Xpdaij

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>sFQ42a

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Hf9t5O

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Ntp9CF

**Comment by Dody2004Sec** [comment]
'"><div rNnTRbt=roann>K8iHk1

**Comment by Dody2004Sec** [comment]
'"></script><div rNnTRbt=roann>4f9RuT

**Comment by Dody2004Sec** [comment]
'" rNnTRbt="roannATTR" x=yyXUDMK

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>gKmfnm

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jsZcy4

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>y5TU8t

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>HnkrA1

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>d39Jg5

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ZVW7iF

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>GfPXdq

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tcrDtt

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>r8iZor

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>NU2KiO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>X3sgwt

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>WDIXyX

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>3RFcTe

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>fNe1Il

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>cb0OC7

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>BfjAvm

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>hNFMwW

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>h1CywF

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>aUb0me

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oBjT4A

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jpH5ty

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>SuoVqM

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>EqqAwF

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>reEcVn

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>4zKvbv

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ThuBGL

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>OixyyY

**Comment by kleinfreund** [comment]
> I'm trying to host my github app on Coolify but it's throwing back this error. Please can you help?

This looks like an issue completely unrelated to semantic-release. It looks like you have disabled cookies in your browser and GitHub as a whole stops working (I don't know this for a fact, but it looks like it from the screenshot).
