### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by maxime1992** [semantic-release/github#285]
Hi, I'm trying to setup a pre release for a given branch and I'm facing the same issue as https://github.com/semantic-release/git/issues/185.

See the last command of the travis job here: https://travis-ci.org/github/cloudnc/ngx-sub-form/builds/726664320

<details>
[10:34:50 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[10:34:50 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[10:34:51 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[10:34:51 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/travis/build/cloudnc/ngx-sub-form/node_modules/@semantic-release/github/lib/get-fail-comment.js:17:10)
    at module.exports (/home/travis/build/cloudnc/ngx-sub-form/node_modules/@semantic-release/github/lib/fail.js:28:74)
    at async fail (/home/travis/build/cloudnc/ngx-sub-form/node_modules/@semantic-release/github/index.js:64:3)
    at async validator (/home/travis/build/cloudnc/ngx-sub-form/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/travis/build/cloudnc/ngx-sub-form/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/travis/build/cloudnc/ngx-sub-form/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as fail] (/home/travis/build/cloudnc/ngx-sub-form/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async callFail (/home/travis/build/cloudnc/ngx-sub-form/node_modules/semantic-release/index.js:235:7)
    at async module.exports (/home/travis/build/cloudnc/ngx-sub-form/node_modules/semantic-release/index.js:264:7)
    at async module.exports (/home/travis/build/cloudnc/ngx-sub-form/node_modules/semantic-release/cli.js:55:5) {
  pluginName: '@semantic-release/github'
}
[10:34:51 PM] [semantic-release] › ✖  EPRERELEASEBRANCH A pre-release branch configuration is invalid in the `branches` configuration.
Each pre-release branch in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches) must have a prerelease property valid per the Semantic Versioning Specification (https://semver.org/#spec-item-9). If the prerelease property is set to true, then the name property is used instead.
</details>

I did upgrade semantic-release to latest (`17.1.1`):

https://github.com/cloudnc/ngx-sub-form/pull/176/commits/12d12b32f775d75438b0a7c75a35ca41448ab0cf

And I'm trying to setup a pre release branch with the following:

https://github.com/cloudnc/ngx-sub-form/pull/176/commits/1e2a3fd5c31f362518bf9791a05659e4770f7f89

```json
{
  "pkgRoot": "dist/ngx-sub-form",
  "branches": [
    "master",
    {
      "name": "feat/rewrite",
      "channel": "beta-rewrite",
      "prerelease": true
    }
  ]
}
```

Am I missing something?

**Comment by travi** [comment]
> EPRERELEASEBRANCH A pre-release branch configuration is invalid in the `branches` configuration. Each pre-release branch in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches) must have a prerelease property valid per the Semantic Versioning Specification (https://semver.org/#spec-item-9). If the prerelease property is set to true, then the name property is used instead.

Your `name` contains a `/`, which is invalid in a pre-release identifier. 

https://semver.org/#spec-item-9

**Comment by maxime1992** [comment]
@travi thanks for having a look :blush: 

I looked into this before I posted the issue but I think I may be missing something. I thought the `name` property was to target a branch and the channel was to let say "rename" it to whatever we want in the version. Is that not correct?

What is channel for exactly then?

Here https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md it says 

> The distribution channel on which to publish releases from this branch. Set to false to force the default distribution channel instead of using the default. See channel.

I'm not sure to understand what that mean and could be missing something obvious :angel:

**Comment by travi** [comment]
> What is channel for exactly then?

npm dist-tags are used to define the distribution channels, which you can learn more about here: https://docs.npmjs.com/adding-dist-tags-to-packages. `channel` defines the dist tag to be used when publishing from this branch.

**Comment by maxime1992** [comment]
Renaming the branch worked indeed.

I'm going to go ahead and close this issue but I think there should be a way to map a branch name to something else so that any branch can be deployed as long as we override the name :) 

Thanks for the help @travi :pray: !

**Comment by travi** [comment]
i happened to be reading the [details of the `prerelease` property](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#prerelease) a bit more closely today and found a detail that i think would help in this situation, if i understand your goal correctly. 

you should be able to use [the `name` property](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#name) to match your branch name, even if it contains characters that are invalid in a pre-release identifier, and then use [the `prerelease` property](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#prerelease) to define the actual pre-release identifier that should be used.
