### ISSUE TITLE
Git tag is missing the tag message option

### ISSUE THREAD

**Issue by TomerFi** [semantic-release/github#393]
**Describe the bug**

Trying to release, when reaching the `tag` phase,
the process fails because the command is missing the `tag message (-m)` option.

From the log:

```text
[10:19:43 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
    at makeError (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async tag (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/lib/git.js:224:3)
    at async run (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:191:5)
    at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 1: git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a',
  command: 'git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a',
  escapedCommand: 'git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'error: Terminal is dumb, but EDITOR unset\n' +
    'Please supply the message using either -m or -F option.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 1: git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
    at makeError (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async tag (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/lib/git.js:224:3)
    at async run (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:191:5)
    at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 1: git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a',
  command: 'git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a',
  escapedCommand: 'git tag 2.0.0 86ecbd244b16a1820d3575eaf4c9698b733e2e2a',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'error: Terminal is dumb, but EDITOR unset\n' +
    'Please supply the message using either -m or -F option.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Process completed with exit code 1.
```

**Github workflow exemplifying the issue**

[A failed run](https://github.com/TomerFi/hebcal-api/runs/3160426582?check_suite_focus=true)
[The workflow](https://github.com/TomerFi/hebcal-api/actions/runs/1067023138/workflow)

**Expected behavior**

I think a feature that allows setting a custom message will be a nice one.
But for the time being, perhaps use the tag version as a tag message as well.

**Additional context**

This issue was originally filed [here](https://github.com/cycjimmy/semantic-release-action/issues/75),
But after skipping the action and trying to work directly with the module, I get the same error.

**Comment by TomerFi** [comment]
Sorry I closed this by mistake.
This is still an issue for me,
I also experience the same with private repos.

The common ground is, I think, none of these projects contain a `package.json` file.

**Comment by LuqWright** [comment]
This issue is still present in 2025.

@TomerFi , were you ever able to find a workaround for this?

**Comment by TomerFi** [comment]
I no longer use this tool, I don't remember what I did, if anything.
