### ISSUE TITLE
Exceeded a secondary rate limit error

### ISSUE THREAD

**Issue by muratcorlu** [semantic-release/github#542]
Recently we hit [an error](https://github.com/Trendyol/baklava/runs/8243633507?check_suite_focus=true) that says 

> You have exceeded a secondary rate limit. Please wait a few minutes before you try again. 

Here is the full log:

```
2022-09-08T07:08:55.0323010Z [7:08:55 AM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/Trendyol/baklava/releases/tag/v2.0.0-beta.24
2022-09-08T07:08:55.0324305Z [7:08:55 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
2022-09-08T07:08:55.0327721Z [7:08:55 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
2022-09-08T07:08:56.1501422Z [7:08:56 AM] [semantic-release] › ✖  Failed step "success" of plugin "@semantic-release/github"
2022-09-08T07:08:56.1540054Z [7:08:56 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
2022-09-08T07:08:56.1541129Z     at /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/@octokit/request/dist-node/index.js:88:21
2022-09-08T07:08:56.1541778Z     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2022-09-08T07:08:56.1542221Z   status: 403,
2022-09-08T07:08:56.1542551Z   response: {
2022-09-08T07:08:56.1544310Z     url: 'https://api.github.com/search/issues?q=repo%3ATrendyol%2Fbaklava+type%3Apr+is%3Amerged+116919c5904430c79d03fb6a5318bedad01ff6c0+04b0023931a27511cd13154811be7d3cbe16f27f+2ad6dfbd6258faf9ae08358a3ad48b96dcd5c714+9fd294cf0ff8aac8cbfd3279f3ff5588420d00a2+75c8ec4eabc331039855982ef9aeca10170ebba4',
2022-09-08T07:08:56.1545489Z     status: 403,
2022-09-08T07:08:56.1545799Z     headers: {
2022-09-08T07:08:56.1546295Z       'access-control-allow-origin': '*',
2022-09-08T07:08:56.1547848Z       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
2022-09-08T07:08:56.1548832Z       connection: 'close',
2022-09-08T07:08:56.1549296Z       'content-encoding': 'gzip',
2022-09-08T07:08:56.1549847Z       'content-security-policy': "default-src 'none'",
2022-09-08T07:08:56.1550783Z       'content-type': 'application/json; charset=utf-8',
2022-09-08T07:08:56.1551324Z       date: 'Thu, 08 Sep 2022 07:08:56 GMT',
2022-09-08T07:08:56.1552018Z       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2022-09-08T07:08:56.1552617Z       server: 'GitHub.com',
2022-09-08T07:08:56.1553253Z       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2022-09-08T07:08:56.1553806Z       'transfer-encoding': 'chunked',
2022-09-08T07:08:56.1554380Z       vary: 'Accept-Encoding, Accept, X-Requested-With',
2022-09-08T07:08:56.1554928Z       'x-content-type-options': 'nosniff',
2022-09-08T07:08:56.1555414Z       'x-frame-options': 'deny',
2022-09-08T07:08:56.1555953Z       'x-github-media-type': 'github.v3; format=json',
2022-09-08T07:08:56.1556556Z       'x-github-request-id': '0442:075D:11E2169:24B2089:63199508',
2022-09-08T07:08:56.1557061Z       'x-ratelimit-limit': '30',
2022-09-08T07:08:56.1557547Z       'x-ratelimit-remaining': '29',
2022-09-08T07:08:56.1558050Z       'x-ratelimit-reset': '1662620996',
2022-09-08T07:08:56.1558543Z       'x-ratelimit-resource': 'search',
2022-09-08T07:08:56.1559458Z       'x-ratelimit-used': '1',
2022-09-08T07:08:56.1560234Z       'x-xss-protection': '0'
2022-09-08T07:08:56.1560597Z     },
2022-09-08T07:08:56.1560829Z     data: {
2022-09-08T07:08:56.1561658Z       documentation_url: 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits',
2022-09-08T07:08:56.1562747Z       message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'
2022-09-08T07:08:56.1563217Z     }
2022-09-08T07:08:56.1563510Z   },
2022-09-08T07:08:56.1563811Z   request: {
2022-09-08T07:08:56.1564195Z     method: 'GET',
2022-09-08T07:08:56.1565935Z     url: 'https://api.github.com/search/issues?q=repo%3ATrendyol%2Fbaklava+type%3Apr+is%3Amerged+116919c5904430c79d03fb6a5318bedad01ff6c0+04b0023931a27511cd13154811be7d3cbe16f27f+2ad6dfbd6258faf9ae08358a3ad48b96dcd5c714+9fd294cf0ff8aac8cbfd3279f3ff5588420d00a2+75c8ec4eabc331039855982ef9aeca10170ebba4',
2022-09-08T07:08:56.1567082Z     headers: {
2022-09-08T07:08:56.1567664Z       accept: 'application/vnd.github.v3+json',
2022-09-08T07:08:56.1568374Z       'user-agent': 'octokit-rest.js/19.0.4 octokit-core.js/4.0.5 Node.js/16.17.0 (linux; x64)',
2022-09-08T07:08:56.1569265Z       authorization: 'token [REDACTED]'
2022-09-08T07:08:56.1569643Z     },
2022-09-08T07:08:56.1570086Z     request: { agent: undefined, hook: [Function: bound bound register] }
2022-09-08T07:08:56.1570485Z   },
2022-09-08T07:08:56.1570948Z   pluginName: '@semantic-release/github'
2022-09-08T07:08:56.1571329Z }
2022-09-08T07:08:56.1571586Z AggregateError: 
2022-09-08T07:08:56.1572056Z     HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
2022-09-08T07:08:56.1572861Z         at /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/@octokit/request/dist-node/index.js:88:21
2022-09-08T07:08:56.1573497Z         at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-09-08T07:08:56.1574356Z     at /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:54:11
2022-09-08T07:08:56.1575378Z     at async Object.pluginsConf.<computed> [as success] (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/[4msemantic-release[24m/lib/plugins/index.js:80:11)
2022-09-08T07:08:56.1576279Z     at async run (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/[4msemantic-release[24m/index.js:209:3)
2022-09-08T07:08:56.1577158Z     at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/[4msemantic-release[24m/index.js:269:22)
2022-09-08T07:08:57.5144060Z     at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/[4msemantic-release[24m/cli.js:55:5)
2022-09-08T07:08:57.5157455Z ##[error]Process completed with exit code 1.
```

I don't see any reason to hit a rate limit on our case. Any idea how to avoid this?

**Comment by muratcorlu** [comment]
We hit same issue [again](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263):

```
[8:38:09 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[448](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:449)
[8:38:11 AM] [semantic-release] › ✖  Failed step "success" of plugin "@semantic-release/github"
[449](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:450)
[8:38:11 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
[450](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:451)
    at /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/@octokit/request/dist-node/index.js:88:21
[451](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:452)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[452](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:453)
  status: 403,
[453](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:454)
  response: {
[454](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:455)
    url: 'https://api.github.com/search/issues?q=repo%3ATrendyol%2Fbaklava+type%3Apr+is%3Amerged+d0d0d0b183e58a37c57b94e49d065d2414f3cb32',
[455](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:456)
    status: 403,
[456](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:457)
    headers: {
[457](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:458)
      'access-control-allow-origin': '*',
[458](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:459)
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
[459](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:460)
      connection: 'close',
[460](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:461)
      'content-encoding': 'gzip',
[461](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:462)
      'content-security-policy': "default-src 'none'",
[462](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:463)
      'content-type': 'application/json; charset=utf-8',
[463](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:464)
      date: 'Tue, 06 Dec 2022 08:38:10 GMT',
[464](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:465)
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
[465](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:466)
      server: 'GitHub.com',
[466](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:467)
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
[467](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:468)
      'transfer-encoding': 'chunked',
[468](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:469)
      vary: 'Accept-Encoding, Accept, X-Requested-With',
[469](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:470)
      'x-content-type-options': 'nosniff',
[470](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:471)
      'x-frame-options': 'deny',
[471](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:472)
      'x-github-api-version-selected': '2022-11-28',
[472](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:473)
      'x-github-media-type': 'github.v3; format=json',
[473](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:474)
      'x-github-request-id': '0742:6CE4:4961EBA:4C5BF62:638EFF72',
[474](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:475)
      'x-ratelimit-limit': '30',
[475](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:476)
      'x-ratelimit-remaining': '29',
[476](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:477)
      'x-ratelimit-reset': '1670315950',
[477](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:478)
      'x-ratelimit-resource': 'search',
[478](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:479)
      'x-ratelimit-used': '1',
[479](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:480)
      'x-xss-protection': '0'
[480](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:481)
    },
[481](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:482)
    data: {
[482](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:483)
      documentation_url: 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits',
[483](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:484)
      message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'
[484](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:485)
    }
[485](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:486)
  },
[486](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:487)
  request: {
[487](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:488)
    method: 'GET',
[488](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:489)
    url: 'https://api.github.com/search/issues?q=repo%3ATrendyol%2Fbaklava+type%3Apr+is%3Amerged+d0d0d0b183e58a37c57b94e49d065d2414f3cb32',
[489](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:490)
    headers: {
[490](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:491)
      accept: 'application/vnd.github.v3+json',
[491](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:492)
      'user-agent': 'octokit-rest.js/19.0.5 octokit-core.js/4.1.0 Node.js/16.18.1 (linux; x64)',
[492](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:493)
      authorization: 'token [REDACTED]'
[493](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:494)
    },
[494](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:495)
    request: { agent: undefined, hook: [Function: bound bound register] }
[495](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:496)
  },
[496](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:497)
  pluginName: '@semantic-release/github'
[497](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:498)
}
[498](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:499)
AggregateError: 
[499](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:500)
    HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
[500](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:501)
        at /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/@octokit/request/dist-node/index.js:88:21
[501](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:502)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
[502](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:503)
    at /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
[503](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:504)
    at async Object.pluginsConf.<computed> [as success] (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:80:11)
[504](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:505)
    at async run (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:209:3)
[505](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:506)
    at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:269:22)
[506](https://github.com/Trendyol/baklava/actions/runs/3627815516/jobs/6118168263#step:8:507)
    at async module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/cli.js:55:5)
```

Do we need to contact with Github for that? Because response headers say like we still have enough remaining requests on rate limits. That's confusing.

**Comment by muratcorlu** [comment]
I just noticed #487.

**Comment by vberlier** [comment]
I'm running into the same issue as well, with the exact same log https://github.com/vberlier/mostly-black/actions/runs/3860576190/jobs/6580998463

**Comment by PythonCoderAS** [comment]
I got this:

```
[5:04:03 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /home/runner/work/github-run-script/github-run-script/node_modules/@octokit/request/dist-node/index.js:78:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/search/issues?q=repo%3APythonCoderAS%2Fgithub-run-script+type%3Apr+is%3Amerged+b1761d916ab5a34a1f26075142646afc12f0639c+426a7674d47511449c5a7033de70fa09a43731e1+76a0466618ccb5ad766e8ec0eacb6315efe8bf29+3b1af928203c075413df16a69b0ca4c314aa236a',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sun, 12 Feb 2023 05:04:03 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '7402:7687:24B33ED:4BF016D:63E87343',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '13',
      'x-ratelimit-reset': '1676178268',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '17',
      'x-xss-protection': '0'
    },
    data: {
      documentation_url: 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits',
      message: 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=repo%3APythonCoderAS%2Fgithub-run-script+type%3Apr+is%3Amerged+b1761d916ab5a34a1f26075142646afc12f0639c+426a7674d47511449c5a7033de70fa09a43731e1+76a0466618ccb5ad766e8ec0eacb6315efe8bf29+3b1af928203c075413df16a69b0ca4c314aa236a',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/19.0.7 octokit-core.js/4.2.0 Node.js/18.14.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  pluginName: '@semantic-release/github'
}
AggregateError: 
    HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
        at /home/runner/work/github-run-script/github-run-script/node_modules/@octokit/request/dist-node/index.js:78:21
    at file:///home/runner/work/github-run-script/github-run-script/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async pluginsConfigAccumulator.<computed> [as success] (file:///home/runner/work/github-run-script/github-run-script/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///home/runner/work/github-run-script/github-run-script/node_modules/semantic-release/index.js:215:3)
    at async Module.default (file:///home/runner/work/github-run-script/github-run-script/node_modules/semantic-release/index.js:275:22)
    at async default (file:///home/runner/work/github-run-script/github-run-script/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
        at /home/runner/work/github-run-script/github-run-script/node_modules/@octokit/request/dist-node/index.js:78:21
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      status: 403,
      response: [Object],
      request: [Object],
      pluginName: '@semantic-release/github'
    }
  ]
}
```

**Comment by erikmartino** [comment]
We run into it too. Could it be implemented by something else than search?

**Comment by PythonCoderAS** [comment]
According to docs, a simple fix is to just wait until the `x-ratelimit-reset` timestamp occurs. Alternatively, I assume search is computationally expensive, so the program should sleep more per search request.

**Comment by gr2m** [comment]
fixed via https://github.com/semantic-release/github/releases/tag/v8.0.8
