### ISSUE TITLE
 An error occurred while running semantic-release: TypeError: this is not a Date object.

### ISSUE THREAD

**Issue by Gokul19797** [semantic-release/github#880]
in the new version of semantic @24.0.0 gettting error  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:22:43 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: this is not a Date object.
    at Proxy.valueOf (<anonymous>)
    at [Symbol.toPrimitive] (<anonymous>)
    at Proxy.toJSON (<anonymous>)
    at JSON.stringify (<anonymous>)
    at stringify (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/utils.js:46:17)
    at getTemplateContext (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/context.js:111:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/template.js:73:33
    at async write (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/writers.js:72:18)
    at async nextAsync (node:internal/streams/from:182:33) {
  pluginName: '@semantic-release/release-notes-generator'
}

**Comment by Gokul19797** [comment]
mentioned wrnlgly
