### ISSUE TITLE
Getting an error during "success" plugin that I need help root-causing

### ISSUE THREAD

**Issue by clarktlaugh** [semantic-release/github#91]
I'm using `semantic-release` in a Drone CI + GitHub Enterprise setup.  I have one project working successfully and have started updating our remaining JS projects to use `semantic-release` as well.  I have run into a failure that I can't easily see what is happening:

This is the output:
```
[Semantic release]: Running semantic-release version 15.7.0
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/npm
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/github
[Semantic release]: Load plugin "analyzeCommits" from @semantic-release/commit-analyzer
[Semantic release]: Load plugin "generateNotes" from @semantic-release/release-notes-generator
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/github
[Semantic release]: Load plugin "success" from @semantic-release/github
[Semantic release]: Load plugin "fail" from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin "verifyConditions"
[Semantic release]: Verify authentication for registry https://registry.npmjs.itcs.hpecorp.net
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Call plugin "verifyConditions"
[Semantic release]: Verify GitHub authentication (https://github.hpe.com/api/v3)
[Semantic release]: Found git tag v1.0.1 associated with version 1.0.1
[Semantic release]: Found 1 commits since last release
[Semantic release]: Call plugin "analyzeCommits"
[Semantic release]: Analyzing commit: fix: replace broken link to wiki
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analysis of 1 commits complete: patch release
[Semantic release]: The next release version is 1.0.2
[Semantic release]: Call plugin "generateNotes"
[Semantic release]: Call plugin "prepare"
[Semantic release]: Wrote version 1.0.2 to package.json
[Semantic release]: Wrote version 1.0.2 to package-lock.json
[Semantic release]: Create tag v1.0.2
[Semantic release]: Call plugin "publish"
[Semantic release]: Publishing version 1.0.2 to npm registry
+ @hpe/zookeeper@1.0.2[Semantic release]: Call plugin "publish"
[Semantic release]: Published GitHub release: https://github.hpe.com/zookeeper/zookeeper/releases/tag/v1.0.2
[Semantic release]: Call plugin "success"
[Semantic release]: An error occurred while running semantic-release: { HttpError: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/enterprise/2.13/v3/search/"}
    at response.text.then.message (/drone/src/github.hpe.com/zookeeper/zookeeper/node_modules/@octokit/rest/lib/request/request.js:78:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  code: 422,
  status: undefined,
  headers:
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers':
      'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'cache-control': 'no-cache',
     connection: 'close',
     'content-length': '322',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Tue, 10 Jul 2018 21:25:03 GMT',
     server: 'GitHub.com',
     status: '422 Unprocessable Entity',
     'strict-transport-security': 'max-age=31536000; includeSubdomains',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-enterprise-version': '2.13.5',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'b811cf9b-3264-43f4-b396-b1b0d84dde6f',
     'x-oauth-scopes': 'repo',
     'x-runtime-rack': '0.058855',
     'x-xss-protection': '1; mode=block' },
  pluginName: '@semantic-release/github' }
{ AggregateError: 
    HttpError: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/enterprise/2.13/v3/search/"}
        at response.text.then.message (/drone/src/github.hpe.com/zookeeper/zookeeper/node_modules/@octokit/rest/lib/request/request.js:78:19)
    at /drone/src/github.hpe.com/zookeeper/zookeeper/node_modules/semantic-release/lib/plugins/pipeline.js:53:11 name: 'AggregateError' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hpe/zookeeper@0.0.0-development semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @hpe/zookeeper@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-10T21_25_03_520Z-debug.log
```

This is my `.drone.yml` pipeline step where I run `semantic-release`:
```
  semantic-release:
    image: node
    commands:
      - npm run semantic-release
    secrets: [ npm_token, github_token ]
```

This is my `.releaserc`:
```
{
    "branch": "master",
    "githubUrl": "https://github.hpe.com",
    "githubApiPathPrefix": "/api/v3"
}
```

It is getting all the way through publishing to our internal npm registry as well as creating the release in GitHub.  The failure seems to be occurring where it is doing some kind of search related to updating issues or PRs?

Is there any additional debugging I can turn on?  Is this something that is possibly documented already that I haven't found?

Thank you in advance

**Comment by clarktlaugh** [comment]
Sorry -- found my problem.  I finally noticed I had an incorrect repository path in `package.json`.  😞
