### ISSUE TITLE
CI failing with error - Field 'canBeRebased' doesn't exist on type 'PullRequest'

### ISSUE THREAD

**Issue by tejasbagal1** [semantic-release/github#910]
Hello Team, 
we use the latest version of semantic-release in our Jenkins pipeline. 
After the recent update https://github.com/semantic-release/github/pull/874 in this repo, our build is failing with the below error

```
3:18:06 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[2024-09-02T19:18:07.347Z] [3:18:06 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/exec"
[2024-09-02T19:18:07.347Z] [3:18:06 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
[2024-09-02T19:18:07.347Z] [3:18:06 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ✘  Failed step "success" of plugin "@semantic-release/github"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/exec"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/exec"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Field 'canBeRebased' doesn't exist on type 'PullRequest'
[2024-09-02T19:18:08.813Z]     at file:///usr/local/lib/node_modules/semantic-release/node_modules/aggregate-error/index.js:23:26
[2024-09-02T19:18:08.813Z]     at Array.map (<anonymous>)
[2024-09-02T19:18:08.813Z]     at new AggregateError (file:///usr/local/lib/node_modules/semantic-release/node_modules/aggregate-error/index.js:16:19)
[2024-09-02T19:18:08.813Z]     at file:///usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.813Z]     at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.813Z]     at async run (file:///usr/local/lib/node_modules/semantic-release/index.js:218:3)
[2024-09-02T19:18:08.813Z]     at async Module.default (file:///usr/local/lib/node_modules/semantic-release/index.js:278:22)
[2024-09-02T19:18:08.814Z]     at async default (file:///usr/local/lib/node_modules/semantic-release/cli.js:55:5) {
[2024-09-02T19:18:08.814Z]   path: [
[2024-09-02T19:18:08.814Z]     'query getAssociatedPRs',
[2024-09-02T19:18:08.814Z]     'repository',
[2024-09-02T19:18:08.814Z]     'commit7c472f',
[2024-09-02T19:18:08.814Z]     '... on Commit',
[2024-09-02T19:18:08.814Z]     'associatedPullRequests',
[2024-09-02T19:18:08.814Z]     'nodes',
[2024-09-02T19:18:08.814Z]     'canBeRebased'
[2024-09-02T19:18:08.814Z]   ],
[2024-09-02T19:18:08.814Z]   extensions: {
[2024-09-02T19:18:08.814Z]     code: 'undefinedField',
[2024-09-02T19:18:08.814Z]     typeName: 'PullRequest',
[2024-09-02T19:18:08.814Z]     fieldName: 'canBeRebased'
[2024-09-02T19:18:08.814Z]   },
[2024-09-02T19:18:08.814Z]   locations: [ { line: 61, column: 19 } ],
[2024-09-02T19:18:08.814Z]   pluginName: '@semantic-release/github'
[2024-09-02T19:18:08.814Z] }
[2024-09-02T19:18:08.814Z] AggregateError: 
[2024-09-02T19:18:08.814Z]     Error: Field 'canBeRebased' doesn't exist on type 'PullRequest'
[2024-09-02T19:18:08.814Z]         at Array.map (<anonymous>)
[2024-09-02T19:18:08.814Z]         at file:///usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.815Z]         at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.815Z]         at async run (file:///usr/local/lib/node_modules/semantic-release/index.js:218:3)
[2024-09-02T19:18:08.815Z]         at async Module.default (file:///usr/local/lib/node_modules/semantic-release/index.js:278:22)
[2024-09-02T19:18:08.815Z]         at async default (file:///usr/local/lib/node_modules/semantic-release/cli.js:55:5)
[2024-09-02T19:18:08.815Z]     at file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.815Z]     at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.816Z]     at async run (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:218:3)
[2024-09-02T19:18:08.816Z]     at async Module.default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:278:22)
[2024-09-02T19:18:08.816Z]     at async default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/cli.js:55:5) {
[2024-09-02T19:18:08.816Z]   errors: [
[2024-09-02T19:18:08.816Z]     Error: Field 'canBeRebased' doesn't exist on type 'PullRequest'
[2024-09-02T19:18:08.816Z]         at file:///usr/local/lib/node_modules/[4msemantic-release[24m/node_modules/[4maggregate-error[24m/index.js:23:26
[2024-09-02T19:18:08.816Z]         at Array.map (<anonymous>)
[2024-09-02T19:18:08.816Z]         at new AggregateError (file:///usr/local/lib/node_modules/[4msemantic-release[24m/node_modules/[4maggregate-error[24m/index.js:16:19)
[2024-09-02T19:18:08.816Z]         at file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.817Z]         at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.817Z]         at async run (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:218:3)
[2024-09-02T19:18:08.817Z]         at async Module.default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:278:22)
[2024-09-02T19:18:08.817Z]         at async default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/cli.js:55:5) {
[2024-09-02T19:18:08.817Z]       path: [36m[Array][39m,
[2024-09-02T19:18:08.817Z]       extensions: [36m[Object][39m,
[2024-09-02T19:18:08.817Z]       locations: [36m[Array][39m,
[2024-09-02T19:18:08.817Z]       pluginName: [32m'@semantic-release/github'[39m
[2024-09-02T19:18:08.818Z]     }
[2024-09-02T19:18:08.818Z]   ]
[2024-09-02T19:18:08.870Z] }
Failed to complete release!
```

We are on GitHub Enterprise Server **`3.9.19`**

Please assist if any changes needs to be made to fix this. Thank you!

**Comment by babblebey** [comment]
Thank you for reporting this... We will look into it.

It appears this has something to do with GitHub Enterprise on Classic PAT Token. Here's a similar case but with another field https://github.com/cli/cli/pull/5779

Cc: @gr2m @jedwards1211

**Comment by jedwards1211** [comment]
@babblebey I bet their GitHub Enterprise has an older version of the GraphQL schema that lacks this `canBeRebased` field.  I guess we should introspect the server's GraphQL schema and adjust the queries we make according to which fields are present?

**Comment by travi** [comment]
> I bet their GitHub Enterprise has an older version of the GraphQL schema that lacks this `canBeRebased` field

since we havent run into problems like that for some time, we havent taken a step we probably should have taken a long time ago. we should define a support policy for GHES versions. starting with something along the lines of "EOL versions of GHES are unsupported here too" would probably be ok. we could point to a reference that lets folks determine which versions have reached EOL. we'd have to decide how GHES versions impact what we consider a breaking change too.

i dont think the version above would fall outside the support range, even if we had a policy defined, but it made my mind revisit this thought

**Comment by jedwards1211** [comment]
`canBeRebased` was added to the GraphQL API [on June 12, 2018](https://docs.github.com/en/graphql/overview/changelog#schema-changes-for-2018-06-12).

However, in GHE < 3.14 this field is a preview feature.

Probably not the best idea but we *could* add [this header](https://docs.github.com/en/enterprise-server@3.10/graphql/overview/schema-previews#merge-info-preview-more-detailed-information-about-a-pull-requests-merge-state-preview) to our GraphQL requests to enable `canBeRebased`:

```
Accept: application/vnd.github.merge-info-preview+json
```

Otherwise, we would just have to conditionally omit the `canBeRebased` field from our queries

**Comment by jedwards1211** [comment]
[GHES 3.11 isn't EOL yet](https://docs.github.com/en/enterprise-server@3.14/admin/all-releases) and it also treats this field as a preview feature, so we'll probably have to fix this issue even if we define a support policy

**Comment by travi** [comment]
> we'll probably have to fix this issue even if we define a support policy

agreed. thanks for confirming

**Comment by babblebey** [comment]
> Otherwise, we would just have to conditionally omit the `canBeRebased` field from our queries

This will not be a good option IMO haha 😃, Feels like plaster and duct-tape... What if another field surfaces?? Plus the fields at the moment are not even rich enough yet, this because we requested those field in the first to allow us build an object to replicate the issue/pull_request api response object as close as possible in order to aid filtering for successComment/releaseLabels.

We might need to add more fields in the future.

> Probably not the best idea but we _could_ add [this header](https://docs.github.com/en/enterprise-server@3.10/graphql/overview/schema-previews#merge-info-preview-more-detailed-information-about-a-pull-requests-merge-state-preview) to our GraphQL requests to enable `canBeRebased`:
> 
> ```
> Accept: application/vnd.github.merge-info-preview+json
> ```

So, I'd say we give this a shot IMO.... simply set the custom media type in the `Accept` header by passing it in the appropriate option at the call of the `octokit.graphql`

What'd you say @travi??

**Comment by aciokler** [comment]
For those looking for a quick workaround you can install the following version for each of the different packages:
```bash
npm install -g semantic-release@24.1.0 @semantic-release/changelog@6.0.3 @semantic-release/commit-analyzer@13.0.0 @semantic-release/exec@6.0.3 @semantic-release/git@10.0.1 @semantic-release/release-notes-generator@14.0.1 @semantic-release/github@10.1.7
```

**Comment by babblebey** [comment]
> in general, we'll need to be careful to ensure that any fields that we use are available on all versions of the api that we consider "supported".

Sure, fow about we just remove the specific field `canBeRebased` **for now**, It was only introduced to help filtering successComments/releaseLabels, but honestly who's consuming it at the moment!? 🤔 

> we'll probably have to fix this issue even if we define a support policy

This way we will be fixing this issue as @jedwards1211 as said
