### ISSUE TITLE
You have exceeded a secondary rate limit in Github Action

### ISSUE THREAD

**Issue by Kaseax** [semantic-release/github#954]
I just wanted to setup semantic-release in my Node-App, but in my Github Action, I'll now get this error - what could I do about this? Did not found anything which could fix it:

```AggregateError: 
    HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID B058:1B07C7:5DD132:B3A100:671BE295.
        at /home/runner/work/website/website/node_modules/semantic-release-plus/node_modules/@octokit/request/dist-node/index.js:122:21
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async requestWithGraphqlErrorHandling (/home/runner/work/website/website/node_modules/semantic-release-plus/node_modules/@octokit/plugin-retry/dist-node/index.js:70:20)
        at async Job.doExecute (/home/runner/work/website/website/node_modules/bottleneck/light.js:405:18)
    at /home/runner/work/website/website/node_modules/semantic-release-plus/lib/plugins/pipeline.js:59:13
    at async pluginsConf.<computed> [as success] (/home/runner/work/website/website/node_modules/semantic-release-plus/lib/plugins/index.js:117:11)
    at async run (/home/runner/work/website/website/node_modules/semantic-release-plus/index.js:280:3)
    at async module.exports (/home/runner/work/website/website/node_modules/semantic-release-plus/index.js:352:22)
    at async module.exports (/home/runner/work/website/website/node_modules/semantic-release-plus/cli.js:102:5)Request quota exhausted for request GET /search/issues```

**Comment by babblebey** [comment]
Hi @Kaseax 

You do not seem to be consuming the appropriate semantic-realease package. Looking at your error, you are consuming `semantic-release-plus`.

Kindly switch to `semantic-release` and try run your action again.

**Comment by Kaseax** [comment]
Hey @babblebey,
Actually, I am using semantic-release itself. 
    "semantic-release": "^24.1.3",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/commit-analyzer": "^13.0.0",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/github": "^11.0.0",
    "@semantic-release/release-notes-generator": "^14.0.1",

I only use @semantic-release-plus/docker for the docker plugin, so I can push a image to the github packages registry. 

Is it still wrong?

**Comment by Kaseax** [comment]
Ah, I understand. Thought it was because of semantic release itself. What would be the best way, to publish the image to a registry then? Seems like the docker plugin isn't up2date. For example Is there a way, to get the version in the CI Configuration? Then I could tag it myself.
